jtype: Flow
version: '1'
with:
  port: 51000
  protocol: http
  cors: true
executors:
  - name: clip_t
    uses:
      jtype: CLIPEncoder
      metas:
        py_modules:
          - clip_server.executors.clip_torch

